# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-01 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zBLOG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='media/zBLOG/upload_images/zBlog_index_image.jpg', upload_to='media/zBLOG/upload_images'),
        ),
    ]
