# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zBLOG', '0003_auto_20181201_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='Read more about the story inside!', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='upload_images/zBlog_index_image.jpg', upload_to='upload_images'),
        ),
    ]
