# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zBLOG', '0003_auto_20181201_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='/zBLOG/upload_images/zBlog_index_image.jpg', upload_to='upload_images'),
        ),
    ]
